# Dataset configuration

In [1]:
!date

Wed Feb 12 00:03:29 JST 2020


In [2]:
import torch
import torch.utils.data
from torchvision import datasets, transforms

# Data loader

In [3]:
def init_dataloader(root="../data/", cuda=False, batch_size=128):
    kwargs = {"num_workers": 1, "pin_memory": True} if cuda else {}
    transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Lambda(lambd=lambda x: x[0]),
    ])

    train_loader = torch.utils.data.DataLoader(
        datasets.MNIST(root, train=True, download=True, transform=transform),
        batch_size=batch_size, shuffle=True, **kwargs,
    )

    test_loader = torch.utils.data.DataLoader(
        datasets.MNIST(root, train=False, transform=transform),
        batch_size=batch_size, shuffle=False, **kwargs,
    )

    return train_loader, test_loader

In [4]:
train_loader, test_loader = init_dataloader()

In [5]:
len(train_loader)

469

In [6]:
len(train_loader.dataset)

60000

In [7]:
train_loader.dataset.data.shape

torch.Size([60000, 28, 28])

In [8]:
_x, _ = iter(train_loader).next()

In [9]:
_x.shape

torch.Size([128, 28, 28])

In [10]:
_x.transpose(0, 1).shape

torch.Size([28, 128, 28])

In [11]:
train_loader.batch_size

128

In [12]:
h = torch.ones(10)

In [13]:
torch.cat([h, h], dim=-1)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.])

In [14]:
h.shape

torch.Size([10])

# Other data loader

In [3]:
def init_dataloader(root="../data/", cuda=False, batch_size=128):
    kwargs = {"num_workers": 1, "pin_memory": True} if cuda else {}
    transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Lambda(lambd=lambda x: x.view(-1)),
    ])

    train_loader = torch.utils.data.DataLoader(
        datasets.MNIST(root, train=True, download=True, transform=transform),
        batch_size=batch_size, shuffle=True, **kwargs,
    )

    test_loader = torch.utils.data.DataLoader(
        datasets.MNIST(root, train=False, transform=transform),
        batch_size=batch_size, shuffle=False, **kwargs,
    )

    return train_loader, test_loader

In [4]:
train_loader, test_loader = init_dataloader()

In [5]:
train_loader.dataset.data.shape

torch.Size([60000, 28, 28])

In [6]:
_x, _ = iter(train_loader).next()

In [7]:
_x.shape

torch.Size([128, 784])

In [8]:
train_loader.dataset.train_data.shape

/Users/ryosuke/anaconda3/envs/pytorch/lib/python3.7/site-packages/torchvision/datasets/mnist.py:55: UserWarning: train_data has been renamed data
  warnings.warn("train_data has been renamed data")


torch.Size([60000, 28, 28])

In [ ]:
train_loader.dataset.

# Dummy latent variable

In [8]:
a = torch.zeros([1, 2, 5])
b = torch.ones([1, 2, 6])

print(a)
print(b)

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]])


In [9]:
torch.cat([a, b], dim=-1)

tensor([[[0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
         [0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.]]])

In [10]:
c = torch.ones([2, 2, 5])

torch.cat([a, c])

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [15]:
e = torch.zeros([2, 5])
f = torch.ones([2, 3])

torch.cat([e, f], dim=-1)

tensor([[0., 0., 0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 0., 0., 1., 1., 1.]])

# $x_t$

In [24]:
x_t = torch.ones(2, 10)

In [25]:
x_t[None, :].size()

torch.Size([1, 2, 10])

In [26]:
x = torch.cat([x_t[None, :] for _ in range(3)], dim=0)

x.size()

torch.Size([3, 2, 10])

In [27]:
x.transpose(0, 1).size()

torch.Size([2, 3, 10])

In [28]:
x.transpose(0, 1)[:, None].size()

torch.Size([2, 1, 3, 10])